Repository team-withiy/withiy-server, pull requests merged in 2025-06, with the labels that each got.

#109 refactor: 프로필 조회 응답에 커플 유무 정보 추가
  src/main/java/com/server/domain/user/dto/UserProfileResponseDto.java
  src/main/java/com/server/domain/user/service/UserService.java
Labels: size/S

#111 refactor: edit delete cascadetype [Place, Photo, Album]
  src/main/java/com/server/domain/album/entity/Album.java
  src/main/java/com/server/domain/category/entity/Category.java
  src/main/java/com/server/domain/photo/entity/Photo.java
  src/main/java/com/server/domain/place/entity/Place.java
Labels: size/S

#118 feat: review & photo ondelete action
  src/main/java/com/server/domain/photo/entity/Photo.java
  src/main/java/com/server/domain/review/entity/Review.java
Labels: size/XS

#119 feat: register & create place
  src/main/java/com/server/domain/album/entity/Album.java
  src/main/java/com/server/domain/album/repository/AlbumRepository.java
  src/main/java/com/server/domain/album/service/AlbumService.java
  src/main/java/com/server/domain/category/entity/Category.java
  src/main/java/com/server/domain/category/repository/CategoryRepository.java
  src/main/java/com/server/domain/photo/controller/PhotoController.java
  src/main/java/com/server/domain/photo/dto/PhotoDto.java
  src/main/java/com/server/domain/photo/entity/Photo.java
  src/main/java/com/server/domain/photo/service/PhotoRepository.java
  src/main/java/com/server/domain/photo/service/PhotoService.java
  src/main/java/com/server/domain/place/controller/PlaceController.java
  src/main/java/com/server/domain/place/dto/CreatePlaceByUserDto.java
  src/main/java/com/server/domain/place/dto/CreatePlaceDto.java
  src/main/java/com/server/domain/place/dto/RegisterPlaceDto.java
  src/main/java/com/server/domain/place/entity/Place.java
  src/main/java/com/server/domain/place/repository/PlaceRepository.java
  src/main/java/com/server/domain/place/service/PlaceService.java
  src/main/java/com/server/domain/review/entity/Review.java
  src/main/java/com/server/domain/review/repository/ReviewRepository.java
  src/main/java/com/server/domain/review/service/ReviewService.java
  src/main/java/com/server/domain/schedule/entity/Schedule.java
  src/main/java/com/server/domain/user/entity/Couple.java
  src/main/java/com/server/domain/user/entity/User.java
  src/main/java/com/server/global/service/ImageService.java
  src/main/java/com/server/global/service/ImageServiceImpl.java
  src/main/java/com/server/global/service/S3ServiceInterface.java
Labels: size/XL

#127 Issue#125/feat/user logout
  src/main/java/com/server/domain/user/controller/UserController.java
  src/main/java/com/server/domain/user/service/UserService.java
  src/main/java/com/server/global/error/handler/GlobalExceptionHandler.java
  src/test/java/com/server/domain/user/service/UserServiceTest.java
Labels: size/M

#129 feat(user): 마이페이지 알림 설정 API
  src/main/java/com/server/domain/user/controller/UserController.java
  src/main/java/com/server/domain/user/dto/NotificationSettingsDto.java
  src/main/java/com/server/domain/user/entity/User.java
  src/main/java/com/server/domain/user/service/UserService.java
  src/test/java/com/server/domain/user/controller/UserControllerTest.java
  src/test/java/com/server/domain/user/service/UserServiceTest.java
Labels: size/L
