Repository team-withiy/withiy-server, pull requests merged in 2025-09, with the labels that each got.

#197 Issue#196/feat/pagination
  src/main/java/com/server/domain/admin/service/AdminFacade.java
  src/main/java/com/server/domain/album/service/AlbumService.java
  src/main/java/com/server/domain/folder/controller/FolderController.java
  src/main/java/com/server/domain/folder/repository/FolderPlaceRepository.java
  src/main/java/com/server/domain/folder/service/FolderFacade.java
  src/main/java/com/server/domain/folder/service/FolderService.java
  src/main/java/com/server/domain/photo/repository/PhotoRepository.java
  src/main/java/com/server/domain/photo/service/PhotoService.java
  src/main/java/com/server/domain/place/repository/PlaceAlbumRepository.java
  src/main/java/com/server/domain/place/repository/PlaceBookmarkRepository.java
  src/main/java/com/server/domain/place/service/PlaceFacade.java
  src/main/java/com/server/domain/place/service/PlaceService.java
  src/main/java/com/server/global/pagination/dto/ApiCursorPaginationRequest.java
  src/main/java/com/server/global/pagination/dto/ApiCursorPaginationResponse.java
  src/main/java/com/server/global/pagination/dto/ApiOffsetPaginationRequest.java
  src/main/java/com/server/global/pagination/dto/ApiOffsetPaginationResponse.java
  src/main/java/com/server/global/pagination/dto/CursorPageDto.java
  src/main/java/com/server/global/pagination/dto/PaginationRequest.java
  src/main/java/com/server/global/pagination/dto/PaginationResponse.java
  src/main/java/com/server/global/pagination/utils/CursorPaginationUtils.java
  src/test/java/com/server/domain/admin/AdminFacadeTest.java
Labels: size/XL

#199 fix: fetch join + pageable 충돌 방지를 위해 fetch join 제거
  http/folder/insert.http
  http/folder/select.http
  http/http-client.env.json
  http/places/insert.http
  src/main/java/com/server/domain/folder/repository/FolderPlaceRepository.java
  src/main/java/com/server/domain/photo/service/PhotoService.java
Labels: size/L

#203 fix: 저장한 모든 장소 조회 로직 임시 수정
  http/http-client.env.json
  src/main/java/com/server/domain/folder/repository/FolderPlaceRepository.java
  src/main/java/com/server/domain/place/service/PlaceService.java
Labels: size/S

#205 fix: 저장한 모든 장소 조회 로직 임시 수정
  http/folder/select.http
  http/http-client.env.json
  src/main/java/com/server/domain/folder/repository/FolderPlaceRepository.java
  src/main/java/com/server/domain/place/service/PlaceService.java
Labels: size/S

#206 fix: 저장한 모든 장소 조회 로직 임시 수정
  http/folder/select.http
  http/http-client.env.json
  src/main/java/com/server/domain/folder/repository/FolderPlaceRepository.java
  src/main/java/com/server/domain/place/service/PlaceService.java
Labels: size/S

#207 fix: 저장한 모든 장소 조회 로직 임시 수정
  http/folder/select.http
  http/http-client.env.json
  src/main/java/com/server/domain/folder/repository/FolderPlaceRepository.java
  src/main/java/com/server/domain/place/service/PlaceService.java
Labels: size/M

#208 fix: 저장한 모든 장소 조회 로직 임시 수정
  http/folder/select.http
  src/main/java/com/server/domain/folder/repository/FolderPlaceRepository.java
Labels: size/XS

#210 fix: 저장한 모든 장소 조회 로직 임시 수정
  http/folder/select.http
  src/main/java/com/server/domain/folder/repository/FolderPlaceRepository.java
  src/main/java/com/server/domain/place/service/PlaceService.java
Labels: size/S

#211 fix: 저장한 모든 장소 조회 로직 임시 수정
  http/http-client.env.json
  src/main/java/com/server/domain/folder/repository/FolderPlaceRepository.java
  src/main/java/com/server/domain/place/service/PlaceService.java
Labels: size/S

#212 fix: 저장한 모든 장소 조회 로직 임시 수정
  src/main/java/com/server/domain/folder/repository/FolderPlaceRepository.java
  src/main/java/com/server/domain/place/service/PlaceService.java
Labels: size/S

#213 Issue#196/feat/pagination
  http/folder/select.http
  src/main/java/com/server/domain/folder/repository/FolderPlaceRepository.java
  src/main/java/com/server/domain/place/service/PlaceService.java
Labels: size/S

#215 fix: 서비스 계층에서 limit 직접 제어하도록 수정
  src/main/java/com/server/domain/folder/controller/FolderController.java
  src/main/java/com/server/domain/folder/repository/FolderPlaceRepository.java
  src/main/java/com/server/domain/folder/service/FolderFacade.java
  src/main/java/com/server/domain/place/service/PlaceService.java
Labels: size/L

#216 fix: Pageable 제거 + limit 직접 제어
  src/main/java/com/server/domain/folder/repository/FolderPlaceRepository.java
  src/main/java/com/server/domain/place/service/PlaceService.java
Labels: size/M

#220 Issue#196/feat/pagination
  http/folder/select.http
  http/http-client.env.json
  src/main/java/com/server/domain/folder/controller/FolderController.java
  src/main/java/com/server/domain/folder/service/FolderFacade.java
  src/main/java/com/server/domain/place/service/PlaceService.java
Labels: size/M

#221 fix:
  http/folder/select.http
  src/main/java/com/server/domain/folder/repository/FolderPlaceRepository.java
  src/main/java/com/server/domain/place/service/PlaceService.java
Labels: size/XS

#222 fix:
  src/main/java/com/server/domain/place/service/PlaceService.java
Labels: size/XS

#223 fix: 커서 기반 페이징 처리 로직 수정
  src/main/java/com/server/domain/folder/controller/FolderController.java
  src/main/java/com/server/domain/folder/repository/FolderPlaceRepository.java
  src/main/java/com/server/domain/folder/service/FolderFacade.java
  src/main/java/com/server/domain/place/repository/PlaceRepository.java
  src/main/java/com/server/domain/place/service/PlaceService.java
  src/main/java/com/server/global/pagination/dto/ApiCursorPaginationRequest.java
  src/main/java/com/server/global/pagination/utils/CursorPaginationUtils.java
Labels: size/L

#224 fix: 커서 기반 페이징 limit 처리 버그 수정
  http/http-client.env.json
  src/main/java/com/server/domain/folder/repository/FolderPlaceRepository.java
  src/main/java/com/server/domain/place/service/PlaceService.java
  src/main/java/com/server/global/pagination/utils/CursorPaginationUtils.java
Labels: size/S

#225 Issue#196/feat/pagination
  src/main/java/com/server/domain/folder/repository/FolderPlaceRepository.java
  src/main/java/com/server/domain/place/service/PlaceService.java
  src/main/java/com/server/global/pagination/dto/ApiCursorPaginationRequest.java
  src/main/java/com/server/global/pagination/utils/CursorPaginationUtils.java
Labels: size/M

#230 Fix/user
  .gitignore
  http/folder/insert.http
  http/folder/select.http
  http/http-client.env.json
  http/places/insert.http
  src/main/java/com/server/domain/photo/repository/PhotoRepository.java
  src/main/java/com/server/domain/photo/service/PhotoService.java
  src/main/java/com/server/domain/place/service/PlaceFacade.java
  src/main/java/com/server/domain/review/controller/ReviewController.java
  src/main/java/com/server/domain/review/dto/CreateReviewRequest.java
  src/main/java/com/server/domain/review/entity/Review.java
  src/main/java/com/server/domain/review/repository/ReviewRepository.java
  src/main/java/com/server/domain/review/service/ReviewFacade.java
  src/main/java/com/server/domain/review/service/ReviewService.java
  src/main/java/com/server/domain/user/entity/User.java
Labels: size/XL

#231 Issue#229/refactor/reviews
  http/http-client.env.json
  src/main/java/com/server/domain/place/controller/PlaceController.java
  src/main/java/com/server/domain/place/service/PlaceFacade.java
  src/main/java/com/server/domain/review/entity/Review.java
  src/main/java/com/server/domain/review/repository/ReviewRepository.java
  src/main/java/com/server/domain/review/service/ReviewService.java
  src/main/java/com/server/global/error/code/ReviewErrorCode.java
Labels: size/L

#233 Issue#232/feat/report
  .gitignore
  http/http-client.env.json
  src/main/java/com/server/domain/report/controller/ReportController.java
  src/main/java/com/server/domain/report/dto/ReportReasonType.java
  src/main/java/com/server/domain/report/dto/ReportTargetType.java
  src/main/java/com/server/domain/report/dto/request/CreateReportRequest.java
  src/main/java/com/server/domain/report/dto/response/GetReportReasonsResponse.java
  src/main/java/com/server/domain/report/entity/Report.java
  src/main/java/com/server/domain/report/repository/ReportRepository.java
  src/main/java/com/server/domain/report/service/ReportFacade.java
  src/main/java/com/server/domain/report/service/ReportService.java
Labels: size/L

#238 Issue#237/feat/search
  src/main/java/com/server/domain/folder/repository/FolderPlaceRepository.java
  src/main/java/com/server/domain/folder/repository/projection/PlaceBookmarkProjection.java
  src/main/java/com/server/domain/folder/service/FolderFacade.java
  src/main/java/com/server/domain/folder/service/FolderService.java
  src/main/java/com/server/domain/photo/repository/PhotoRepository.java
  src/main/java/com/server/domain/photo/service/PhotoService.java
  src/main/java/com/server/domain/place/controller/PlaceController.java
  src/main/java/com/server/domain/place/dto/CreatePlaceDto.java
  src/main/java/com/server/domain/place/dto/GetPlaceDetailResponse.java
  src/main/java/com/server/domain/place/dto/LocationDto.java
  src/main/java/com/server/domain/place/dto/PlaceDetailDto.java
  src/main/java/com/server/domain/place/dto/PlaceDto.java
  src/main/java/com/server/domain/place/dto/UpdatePlaceDto.java
  src/main/java/com/server/domain/place/dto/reqeust/NearbyPlaceRequest.java
  src/main/java/com/server/domain/place/dto/response/NearbyPlaceResponse.java
  src/main/java/com/server/domain/place/entity/Place.java
  src/main/java/com/server/domain/place/repository/PlaceRepository.java
  src/main/java/com/server/domain/place/service/PlaceFacade.java
  src/main/java/com/server/domain/place/service/PlaceService.java
  src/main/java/com/server/domain/review/repository/ReviewRepository.java
  src/main/java/com/server/domain/review/repository/projection/PlaceScoreProjection.java
  src/main/java/com/server/domain/review/service/ReviewService.java
Labels: size/L

#242 feat : 일정 추가, 조회, 수정 API 개발
  src/main/java/com/server/domain/album/entity/Album.java
  src/main/java/com/server/domain/album/entity/AlbumPhoto.java
  src/main/java/com/server/domain/album/repository/AlbumPhotoRepository.java
  src/main/java/com/server/domain/album/repository/AlbumRepository.java
  src/main/java/com/server/domain/album/service/AlbumService.java
  src/main/java/com/server/domain/category/service/CategoryService.java
  src/main/java/com/server/domain/dateSchedule/controller/DateScheduleController.java
  src/main/java/com/server/domain/dateSchedule/dto/DateSchedCreateRequest.java
  src/main/java/com/server/domain/dateSchedule/dto/DateSchedPlaceDto.java
  src/main/java/com/server/domain/dateSchedule/dto/DateSchedResponse.java
  src/main/java/com/server/domain/dateSchedule/dto/DateSchedUpdatePlaceDto.java
  src/main/java/com/server/domain/dateSchedule/dto/DateSchedUpdateRequest.java
  src/main/java/com/server/domain/dateSchedule/entity/DateSchedule.java
  src/main/java/com/server/domain/dateSchedule/repository/DateSchedRepository.java
  src/main/java/com/server/domain/dateSchedule/service/DateSchedFacade.java
  src/main/java/com/server/domain/dateSchedule/service/DateSchedService.java
  src/main/java/com/server/domain/photo/entity/Photo.java
  src/main/java/com/server/domain/photo/service/PhotoService.java
  src/main/java/com/server/domain/place/dto/PlaceStatus.java
  src/main/java/com/server/domain/place/entity/Place.java
  src/main/java/com/server/domain/place/entity/PlaceReview.java
  src/main/java/com/server/domain/place/repository/PlaceReviewRepository.java
  src/main/java/com/server/domain/place/service/PlaceFacade.java
  src/main/java/com/server/domain/place/service/PlaceReviewService.java
  src/main/java/com/server/domain/place/service/PlaceService.java
  src/main/java/com/server/domain/route/dto/RouteStatus.java
  src/main/java/com/server/domain/route/entity/Route.java
  src/main/java/com/server/global/common/BaseTime.java
  src/main/java/com/server/global/error/code/DateSchedErrorCode.java
  src/main/java/com/server/global/error/handler/GlobalExceptionHandler.java
  src/main/java/com/server/global/validation/DateFormat.java
  src/main/java/com/server/global/validation/DateFormatValidator.java
  src/test/java/com/server/domain/controller/DateScheduleControllerTest.java
Labels: size/XXL

#241 Issue#240/feat/kakao map
  src/main/java/com/server/domain/folder/repository/FolderPlaceRepository.java
  src/main/java/com/server/domain/map/controller/MapController.java
  src/main/java/com/server/domain/map/dto/MapPlaceDto.java
  src/main/java/com/server/domain/map/dto/PlaceDto.java
  src/main/java/com/server/domain/map/dto/response/CategorySearchResponse.java
  src/main/java/com/server/domain/map/dto/response/KeywordSearchResponse.java
  src/main/java/com/server/domain/map/service/MapService.java
  src/main/java/com/server/domain/photo/service/PhotoService.java
  src/main/java/com/server/domain/place/controller/PlaceController.java
  src/main/java/com/server/domain/place/dto/LocationDto.java
  src/main/java/com/server/domain/place/dto/request/NearbyPlaceRequest.java
  src/main/java/com/server/domain/place/entity/Place.java
  src/main/java/com/server/domain/place/repository/PlaceRepository.java
  src/main/java/com/server/domain/place/service/PlaceFacade.java
  src/main/java/com/server/domain/place/service/PlaceService.java
  src/main/java/com/server/domain/route/repository/RouteBookmarkRepository.java
  src/main/java/com/server/domain/search/controller/SearchController.java
  src/main/java/com/server/domain/search/service/SearchFacade.java
  src/main/java/com/server/global/error/handler/FilterChainExceptionHandler.java
Labels: size/L
